service: api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: programmaticServerless
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:*
          Resource: '*'

  httpApi:
    cors: true

functions:
  sendEmail:
    handler: sendEmail.handler
    events:
      - httpApi:
          path: /send-email
          method: POST
